### PR TITLE
Rename ASWF-WIP to aswf in response to formal acceptance

### PR DESCRIPTION
**Pull request by michdolan**
Officially culling the WIP ASWF status now that we've been accepted.

### CODE REVIEW

**Comment by lgritz** [comment]
I believe that John Mertic suggested to me that it might be preferable for the DCO file to just refer to the canonical one on the web, rather than reproduce the text inline, if you know what I mean.

**Comment by michdolan** [comment]
Oh, so just have one line with a URL to:

https://developercertificate.org/

**Comment by lgritz** [comment]
Yeah, that was John's recommendation.

**Comment by lgritz** [comment]
Other than that, the renaming LGTM.

**Comment by michdolan** [comment]
DCO contents have now been replaced with the URL

**Comment by michdolan** [comment]
Good point Doug.

**Comment by michdolan** [comment]
24 hour merge warning. Please have a look if you haven't yet.

**Pull request merged**
