### PR TITLE
Hodoulp/fix windows build with vc14

### LINKED ISSUE #446: Compiling Issues on Windows with Visual Studio 2017 BuildTools
Hi,

I'm trying to build OCIO on _Windows_ with _Visual Studio 2017 BuildTools_ and _CMake_, it is kind of painful so far. This is my _CMake_ command:

> cmake D:\Documents\Development\ThirdParty\opencolorio\OpenColorIO -DCMAKE_INSTALL_PREFIX=D:\Documents\Development\ThirdParty\opencolorio/build\release -DBOOST_ROOT=C:\Users\thomas\Packages\boost\1.64.0\platform-windows\boost -DOCIO_USE_BOOST_PTR=ON -G "Visual Studio 15 Win64" -T v141,host=x64

- I had to set `OCIO_USE_BOOST_PTR=ON` and modify the **CMakeLists.txt** file to add the `1.64.0`  version.
- **ociocheck** **CMakeLists.txt** file `include_directories` statement is missing a _boost_ include: `    ${Boost_INCLUDE_DIR}`
- **ThirdParty\opencolorio\OpenColorIO\src\apps\share\argparse.cpp** is missing an include for `std::max`: `#include <algorithm>`
- **ociocheck** still raises a ton of linkage errors after that:
```
"D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\INSTALL.vcxproj" (default target) (1) ->
"D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\ALL_BUILD.vcxproj" (default target) (3) ->
"D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj" (default target) (10) ->
(Link target) -> 
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * __cdecl OpenColorIO::v1::GetVersion(void)" (__imp_?GetVersion@v1@OpenColorIO@@YAPEBDXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) int __cdecl OpenColorIO::v1::GetVersionHex(void)" (__imp_?GetVersionHex@v1@OpenColorIO@@YAHXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class boost::shared_ptr<class OpenColorIO::v1::Config const > __cdecl OpenColorIO::v1::Config::CreateFromEnv(void)" (__imp_?CreateFromEnv@Config@v1@OpenColorIO@@SA?AV?$shared_ptr@$$CBVConfig@v1@OpenColorIO@@@boost@@XZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class boost::shared_ptr<class OpenColorIO::v1::Config const > __cdecl OpenColorIO::v1::Config::CreateFromFile(char const *)" (__imp_?CreateFromFile@Config@v1@OpenColorIO@@SA?AV?$shared_ptr@$$CBVConfig@v1@OpenColorIO@@@boost@@PEBD@Z) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl OpenColorIO::v1::Config::sanityCheck(void)const " (__imp_?sanityCheck@Config@v1@OpenColorIO@@QEBAXXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl OpenColorIO::v1::Config::serialize(class std::basic_ostream<char,struct std::char_traits<char> > &)const " (__imp_?serialize@Config@v1@OpenColorIO@@QEBAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl OpenColorIO::v1::Config::getSearchPath(void)const " (__imp_?getSearchPath@Config@v1@OpenColorIO@@QEBAPEBDXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl OpenColorIO::v1::Config::getWorkingDir(void)const " (__imp_?getWorkingDir@Config@v1@OpenColorIO@@QEBAPEBDXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl OpenColorIO::v1::Config::getNumColorSpaces(void)const " (__imp_?getNumColorSpaces@Config@v1@OpenColorIO@@QEBAHXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl OpenColorIO::v1::Config::getColorSpaceNameByIndex(int)const " (__imp_?getColorSpaceNameByIndex@Config@v1@OpenColorIO@@QEBAPEBDH@Z) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class boost::shared_ptr<class OpenColorIO::v1::ColorSpace const > __cdecl OpenColorIO::v1::Config::getColorSpace(char const *)const " (__imp_?getColorSpace@Config@v1@OpenColorIO@@QEBA?AV?$shared_ptr@$$CBVColorSpace@v1@OpenColorIO@@@boost@@PEBD@Z) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl OpenColorIO::v1::Config::getNumRoles(void)const " (__imp_?getNumRoles@Config@v1@OpenColorIO@@QEBAHXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl OpenColorIO::v1::Config::getRoleName(int)const " (__imp_?getRoleName@Config@v1@OpenColorIO@@QEBAPEBDH@Z) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl OpenColorIO::v1::Config::getDefaultDisplay(void)const " (__imp_?getDefaultDisplay@Config@v1@OpenColorIO@@QEBAPEBDXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl OpenColorIO::v1::Config::getDefaultView(char const *)const " (__imp_?getDefaultView@Config@v1@OpenColorIO@@QEBAPEBDPEBD@Z) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl OpenColorIO::v1::Config::getNumLooks(void)const " (__imp_?getNumLooks@Config@v1@OpenColorIO@@QEBAHXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl OpenColorIO::v1::Config::getLookNameByIndex(int)const " (__imp_?getLookNameByIndex@Config@v1@OpenColorIO@@QEBAPEBDH@Z) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class boost::shared_ptr<class OpenColorIO::v1::Processor const > __cdecl OpenColorIO::v1::Config::getProcessor(class boost::shared_ptr<class OpenColorIO::v1::ColorSpace const > const &,class boost::shared_ptr<class OpenColorIO::v1::ColorSpace const > const &)const " (__imp_?getProcessor@Config@v1@OpenColorIO@@QEBA?AV?$shared_ptr@$$CBVProcessor@v1@OpenColorIO@@@boost@@AEBV?$shared_ptr@$$CBVColorSpace@v1@OpenColorIO@@@5@0@Z) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char const * __cdecl OpenColorIO::v1::ColorSpace::getName(void)const " (__imp_?getName@ColorSpace@v1@OpenColorIO@@QEBAPEBDXZ) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_DEFAULT" (__imp_?ROLE_DEFAULT@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_REFERENCE" (__imp_?ROLE_REFERENCE@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_DATA" (__imp_?ROLE_DATA@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_COLOR_PICKING" (__imp_?ROLE_COLOR_PICKING@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_SCENE_LINEAR" (__imp_?ROLE_SCENE_LINEAR@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_COMPOSITING_LOG" (__imp_?ROLE_COMPOSITING_LOG@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_COLOR_TIMING" (__imp_?ROLE_COLOR_TIMING@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_TEXTURE_PAINT" (__imp_?ROLE_TEXTURE_PAINT@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
  main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) char const * const OpenColorIO::v1::ROLE_MATTE_PAINT" (__imp_?ROLE_MATTE_PAINT@v1@OpenColorIO@@3PEBDEB) referenced in function main [D:\Documents\Development\ThirdParty\opencolorio\build\OpenColorIO\src\apps\ociocheck\ociocheck.vcxproj]
```
- **ociobakelut** cannot compile because of call to `configure` for **LCMS**.

I managed to compile the project by commenting out the build of **ociocheck** and **ociobakelut**, I'm not sure the dll works at all as I have a ton of _inconsistent dll linkage_ warnings.

Here is the output without commenting  **ociocheck** and **ociobakelut** builds: https://gist.github.com/KelSolaar/7418cda901e4910fb090494e41d47353

### PR DESCRIPTION
**Pull request by hodoulp**
* Fixed several issues related to the Windows VC++14 build settings
* Fixed some warnings
* Fixed some bugs
* Travis CUI builds success

closes #446

### CODE REVIEW

**Comment by KelSolaar** [comment]
Thanks @hodoulp! I'll test that at work next week.

**Comment by hodoulp** [comment]
The goal of the pull request is to integrate some fixes I did on Windows 7 & VC++14 while investigating the library code. The first problems were around the build in release mode which was creating some libraries & apps in debug mode (and surprisingly several build breaks too). I've tried also the reduce the number of warnings (still many are present). Finally, I fixed the target MainTests & test code so that unit tests now succeed, and the target could now be used by the build system.

**Comment by KelSolaar** [comment]
I successfully compiled OpenColorIO with Python bindings on Windows 10 using your PR + https://github.com/imageworks/OpenColorIO/pull/457 @hodoulp!

I need more testing but seems great so far! 


```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\thomas>rez-env opencolorio -- python
Python 2.7.13 |Continuum Analytics, Inc.| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import PyOpenColorIO
>>> dir(PyOpenColorIO)
['AllocationTransform', 'Baker', 'CDLTransform', 'ClearAllCaches', 'ColorSpace', 'ColorSpaceTransform', 'Config', 'Constants', 'Context', 'DisplayTransform', 'Exception', 'ExceptionMissingFile', 'ExponentTransform', 'FileTransform', 'GetCurrentConfig', 'GetLoggingLevel', 'GpuShaderDesc', 'GroupTransform', 'LogTransform', 'Look', 'LookTransform', 'MatrixTransform', 'Processor', 'ProcessorMetadata', 'SetCurrentConfig', 'SetLoggingLevel', 'Transform', '__doc__', '__file__', '__name__', '__package__', 'hexversion', 'version']
>>> PyOpenColorIO.version
'1.0.9'
>>>
```

**Comment by hodoulp** [comment]
In case you would like to compile on Windows, below is my batch file:

`@echo off


REM Grab the repo name, default is ocio_rw
set repo_name=ocio_rw
if not %1.==. set repo_name=%1


set CYGWIN=nodosfilewarning

set CMAKE_PATH=D:\Shotgun\external\cmake-3.7.2
set PYTHON_PATH=C:\Python27

set PATH=D:\Tools\cygwin64\bin;%CMAKE_PATH%\bin;%PYTHON_PATH%;D:\OpenSource\ninja;%PATH%

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64


set BOOST_ROOT=D:\SolidAngle\boost_1_55_0
set OCIO_PATH=D:\OpenSource\%repo_name%


@doskey ne="D:\Tools\Notepad++\notepad++.exe" -nosession -multiInst $*
@doskey sub="D:\Tools\Sublime Text 3\subl.exe" --project %OCIO_PATH%_project.sublime-project


REM Decompose the directory change to avoid problems...
D:

IF NOT EXIST %OCIO_PATH% ( 
echo %OCIO_PATH% does not exist
exit /b
)
cd %OCIO_PATH%


set CMAKE_BUILD_TYPE=Release

echo *******
echo *********************************************
echo ******* Building %OCIO_PATH%
echo **
echo **
set are_you_sure = Y
set /P are_you_sure=Build in %CMAKE_BUILD_TYPE% ([Y]/N)?  
if not %are_you_sure%==Y set CMAKE_BUILD_TYPE=Debug


set BUILD_PATH=_build_rls
if not %CMAKE_BUILD_TYPE%==Release set BUILD_PATH=_build_dbg

IF NOT EXIST %BUILD_PATH% ( mkdir %BUILD_PATH% )
cd %BUILD_PATH%


echo **
echo **

cmake -G "NMake Makefiles" ^
    -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ^
    -DCMAKE_INSTALL_PREFIX=%OCIO_PATH%\_install ^
    -DOCIO_BUILD_TESTS=ON ^
    %OCIO_PATH%

set PATH=%OCIO_PATH%\%BUILD_PATH%\src\core;%PATH%


REM Find the current branch
set GITBRANCH=
for /f %%I in ('git.exe rev-parse --abbrev-ref HEAD 2^> NUL') do set GITBRANCH=%%I

if not "%GITBRANCH%" == ""  prompt $C%GITBRANCH%$F $P$G 


echo *******
echo *********************************************
echo boost    = %BOOST_ROOT%
echo cmake    = %CMAKE_PATH%
echo *******
if not "%GITBRANCH%" == "" echo branch  = %GITBRANCH%
echo *******
echo Mode    = %CMAKE_BUILD_TYPE%
echo path    = %OCIO_PATH%\%BUILD_PATH%
echo compile = nmake all
echo test    = nmake test
echo *********************************************
echo *******`

**Pull request merged**
