### PR TITLE
use macOS & cmake 3.11+

### PR DESCRIPTION
**Pull request by retokromer**
- use `macOS` rather than `OS X`
- at least `cmake 3.10` is required, according to
https://github.com/imageworks/OpenColorIO/blob/45652448348c844828df3d165d68dc10b8ec6135/CMakeLists.txt#L1

### CODE REVIEW

**Comment by michdolan** [comment]
Noting that PR #771 bumps the minimum CMake version to 3.11, which is the current minimum of OpenEXR 2.3.0.

**Comment by retokromer** [comment]
@michdolan Thank you for the information! It seems that I don’t have the rights to update my patch to `3.11`.

**Comment by michdolan** [comment]
You should be able to push another commit to the branch in your fork and it will appear here automatically. You may need to pull first to get the commits we've been triggering from GH to bring your branch up to date with master.

**Comment by hodoulp** [comment]
@retokromer When you will have some time, the branch is only waiting for a minor change and an update before being merge.

**Comment by retokromer** [comment]
>When you will have some time

@hodoulp Sorry, I’m not sure I understand you carefully: Is there any action needed on my end?

**Comment by hodoulp** [comment]
@retokromer The change is already done in CMakeLists.txt (by the pull request #771). But your pull request can update the documented CMake minimal version to 3.11 (i.e. the `docs/installation.rst`).

**Comment by retokromer** [comment]
@hodoulp I’m afraid, I cannot find the correct branch. When I push from my local one, I got a 403 error.

**Comment by retokromer** [comment]
@hodoulp I think so, but I might have made something wrong. What seems strange to me is that the working branch is now labeled `unknown repository`. I’m afraid, I don’t know how to fix that… possibly close this PR and open another one?

**Comment by hodoulp** [comment]
@retokromer As the pull request changed only one file, you could recreate the pull request if you can't resolve the problem.

I found some potential explanation/solution [here](https://stackoverflow.com/questions/36071272/fix-unknown-repository-of-an-opened-pr-after-deleted-the-fork) if you want to try.

**Comment by retokromer** [comment]
Superseded by https://github.com/imageworks/OpenColorIO/pull/813

**Pull request closed without merging**
