### PR TITLE
Create COMMITTERS.md

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by hodoulp** [comment]
**[Question]** After reading the list of names, I think that we should update the permissions before merging anything. What do you think?

**Comment by michdolan** [comment]
Is your thought to reduce admins to those who have committed in the last 2 or so years?

**Comment by hodoulp** [comment]
That's a topic for a TSC meeting. But the idea would be to have some kind of exit process after X years without any activities (i.e. any kind of activities from commits to TSC participation).
The goal is not to 'downgrade' someone but to keep/increase his interest in OCIO or to promote some else.

**Comment by michdolan** [comment]
Sounds good @hodoulp . Let's discuss Monday.

**Pull request merged**
