### PR TITLE
Update CCLA from changes needed to work in the CLA system

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by lgritz** [comment]
LGTM

**Comment by jmertic** [comment]
Hey @doug-walker, thanks for having your legal review.

These changes are more to make it work in the new CLA system ( mainly by adding the CLA manager role definition ), it's not going to be the exact same CLA as the other ASWF projects. Feel free to have your legal reach out to me and I can connect them with Steve Winslow if there are any questions.

**Comment by lgritz** [comment]
I assume it's ok for a company to name multiple CLA managers?

**Comment by jmertic** [comment]
@lgritz Yes

**Pull request merged**
