### PR TITLE
hotfix Lut1DOp negative value clamp

### PR DESCRIPTION
**Pull request by scoopxyz**
address issue #399

### CODE REVIEW

**Comment by KevinJW** [comment]
If I am reading the patch right ... I'm not sure it should clamp at zero, but at the LUT minimum - depending on the direction this would be the first value in the LUT  (simple_lut[indexLow] ?) or the lower bound in the range (*start ?), - on the assumption of monotonicity.

As a note at one point I did try just adding extra entries to the LUTs at the bottom end and clamping them to a minimum on he assumption that extrapolation of flat values would also effectively clamp - but it didn't.

Kevin

**Comment by scoopxyz** [comment]
This implementation provides the above behavior via it's encapsulating function "Lut1D_LinearInverse" which stores the values via a _**mx+b**_ format, where the clamped function returns 0.0 as _**x**_ when the value becomes negative. Since _b == lut.from_min_ it will return the expected _from_min_ value. This has been the behavior in the tests I have run.

I've removed the initial clamp from the forward transform as I don't believe that will result in desired behavior.

**Comment by scoopxyz** [comment]
Would we be able to get some extra eyes on this @malcolmhumphreys @Shootfast @KevinJW as this is directly impacting imagery in current OCIO ACES implementations?

If my solution is too simplistic I'd be happy to work on a more comprehensive solution in due time.

**Comment by scoopxyz** [comment]
Conversation with @Dithermaster reveals that "Jeremy said it was a bug - the intent was for clamping (not extrapolation)"

After a successful Travis build I intend to merge the above.

**Comment by Dithermaster** [comment]
Digging up an old email, Jeremy had this to say: "I consider the correct behavior to be clamping values outside the defined range" and "I submitted an issue report on it when discovered earlier this year: https://github.com/imageworks/OpenColorIO/issues/326"

**Comment by Dithermaster** [comment]
This fix looks like it would fix the errant extrapolation on the bottom end. I agree that the `lut.from_min` is handled in the caller, not this function.

**Pull request merged**
