### PR TITLE
CI branch cleanup RB-1.1

### PR DESCRIPTION
**Pull request by michdolan**
RB-1.1 counterpart to #797 . Note: The branch filter is here more to communicate intent than out of technical necessity.

Update:
Fixed a self-assign-field warning breaking the Linux build in Travis, which has already been done in master.

### CODE REVIEW

**Comment by hodoulp** [comment]
As discussed during the TSC meeting, I checked the branch and found only one issue for the Linux gcc 5.4.0 builds:

`Scanning dependencies of target PyOpenColorIO`
`[ 35%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyAllocationTransform.cpp.o`
`/home/travis/build/imageworks/OpenColorIO/src/pyglue/PyAllocationTransform.cpp:56:20: error: ‘PyObject* OpenColorIO::v1::{anonymous}::PyOCIO_AllocationTransform_equals(PyObject*, PyObject*)’ declared ‘static’ but never defined [-Werror=unused-function]`
`         PyObject * PyOCIO_AllocationTransform_equals(PyObject * self,  PyObject`
`                    ^`
`cc1plus: all warnings being treated as errors`
`src/pyglue/CMakeFiles/PyOpenColorIO.dir/build.make:66: recipe for target 'src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyAllocationTransform.cpp.o' failed`
`make[2]: *** [src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyAllocationTransform.cpp.o] Error 1`

The fix consists to remove the line 56 in the file `OpenColorIO/src/pyglue/PyAllocationTransform.cpp` as there is no equal method for the AllocationTransform class `OpenColorIO/export/OpenColorIO/OpenColorTransforms.h`.

**Comment by hodoulp** [comment]
The Linux clang 7.0.0 build fails because it compiles with C++11 or higher. The idea is to impose C++98 (instead of the compiler default C++ version which changes between compiler versions). The solution is at least to add `set(CMAKE_CXX_STANDARD 98)` in the `OpenColorIO/CMakeLists.txt`.

**Comment by michdolan** [comment]
I'm going to close and reopen this PR to trigger a new CI run with AppVeyor.

**Comment by michdolan** [comment]
Thanks for the suggested fixes @hodoulp . That fixed the Linux builds.

**Pull request merged**
