### PR TITLE
Add Docker reference build environment

### PR DESCRIPTION
**Pull request by scoopxyz**
To aid developers I'm looking to add reference development environments using the Docker platform. Ideally we'd supply all supported build matrices for Linux and host pre-built images on Docker Hub.

As an initial draft, this PR is open to review and comment on Repo structure and dependencies within this first draft.

For an estimate, it takes approximately **44 minutes to build from scratch** on a Macbook Air with 2GB & 2 cores allocated and results in a **2.84 GB image**

Here are the current dependencies included:

```
Docker Image

Base OS: Centos 7

================================================================================
 Package                      Arch   Version                      Repository
                                                                           Size
================================================================================
Installing:
 bzip2                        x86_64 1.0.6-13.el7                 base     52 k
 bzip2-devel                  x86_64 1.0.6-13.el7                 base    218 k
 cmake3                       x86_64 3.6.3-1.el7                  epel    6.4 M
 file                         x86_64 5.11-33.el7                  base     57 k
 freeglut-devel               x86_64 2.8.1-3.el7                  base    114 k
 gcc-c++                      x86_64 4.8.5-16.el7                 base    7.2 M
 git                          x86_64 1.8.3.1-12.el7_4             updates 4.4 M
 glew-devel                   x86_64 1.10.0-5.el7                 base    172 k
 java-1.8.0-openjdk           x86_64 1:1.8.0.151-1.b12.el7_4      updates 241 k
 libXi-devel                  x86_64 1.7.9-1.el7                  base    105 k
 libXmu-devel                 x86_64 1.1.2-2.el7                  base     24 k
 libjpeg-turbo-devel          x86_64 1.2.90-5.el7                 base     98 k
 libpng-devel                 x86_64 2:1.5.13-7.el7_2             base    122 k
 libtiff-devel                x86_64 4.0.3-27.el7_3               base    473 k
 make                         x86_64 1:3.82-23.el7                base    420 k
 patch                        x86_64 2.7.1-8.el7                  base    110 k
 python-devel                 x86_64 2.7.5-58.el7                 base    395 k
 python-sphinx                noarch 1.1.3-11.el7                 base    1.1 M
 wget                         x86_64 1.14-15.el7_4.1              updates 547 k
 which                        x86_64 2.20-7.el7                   base     41 k
Installing for dependencies:
 alsa-lib                     x86_64 1.1.3-3.el7                  base    421 k
 cmake3-data                  noarch 3.6.3-1.el7                  epel    1.1 M
 copy-jdk-configs             noarch 2.2-3.el7                    base     18 k
 cpp                          x86_64 4.8.5-16.el7                 base    5.9 M
 emacs-filesystem             noarch 1:24.3-20.el7_4              updates  58 k
 fipscheck                    x86_64 1.4.1-6.el7                  base     21 k
 fipscheck-lib                x86_64 1.4.1-6.el7                  base     11 k
 fontconfig                   x86_64 2.10.95-11.el7               base    229 k
 fontpackages-filesystem      noarch 1.44-8.el7                   base    9.9 k
 freeglut                     x86_64 2.8.1-3.el7                  base    182 k
 freetype                     x86_64 2.4.11-15.el7                base    392 k
 gcc                          x86_64 4.8.5-16.el7                 base     16 M
 giflib                       x86_64 4.1.6-9.el7                  base     40 k
 gl-manpages                  noarch 1.1-7.20130122.el7           base    994 k
 glibc-devel                  x86_64 2.17-196.el7                 base    1.1 M
 glibc-headers                x86_64 2.17-196.el7                 base    675 k
 groff-base                   x86_64 1.22.2-8.el7                 base    942 k
 hwdata                       x86_64 0.252-8.6.el7                base    2.2 M
 java-1.8.0-openjdk-headless  x86_64 1:1.8.0.151-1.b12.el7_4      updates  32 M
 javapackages-tools           noarch 3.4.1-11.el7                 base     73 k
 jbigkit-libs                 x86_64 2.0-11.el7                   base     46 k
 jsoncpp                      x86_64 0.10.5-2.el7                 epel     82 k
 kernel-headers               x86_64 3.10.0-693.5.2.el7           updates 6.0 M
 less                         x86_64 458-9.el7                    base    120 k
 libGLEW                      x86_64 1.10.0-5.el7                 base    134 k
 libGLEWmx                    x86_64 1.10.0-5.el7                 base    124 k
 libICE                       x86_64 1.0.9-9.el7                  base     66 k
 libICE-devel                 x86_64 1.0.9-9.el7                  base     50 k
 libSM                        x86_64 1.2.2-2.el7                  base     39 k
 libSM-devel                  x86_64 1.2.2-2.el7                  base     13 k
 libX11                       x86_64 1.6.5-1.el7                  base    606 k
 libX11-common                noarch 1.6.5-1.el7                  base    164 k
 libX11-devel                 x86_64 1.6.5-1.el7                  base    980 k
 libXau                       x86_64 1.0.8-2.1.el7                base     29 k
 libXau-devel                 x86_64 1.0.8-2.1.el7                base     14 k
 libXcomposite                x86_64 0.4.4-4.1.el7                base     22 k
 libXdamage                   x86_64 1.1.4-4.1.el7                base     20 k
 libXdamage-devel             x86_64 1.1.4-4.1.el7                base    9.7 k
 libXext                      x86_64 1.3.3-3.el7                  base     39 k
 libXext-devel                x86_64 1.3.3-3.el7                  base     75 k
 libXfixes                    x86_64 5.0.3-1.el7                  base     18 k
 libXfixes-devel              x86_64 5.0.3-1.el7                  base     13 k
 libXfont                     x86_64 1.5.2-1.el7                  base    152 k
 libXi                        x86_64 1.7.9-1.el7                  base     40 k
 libXmu                       x86_64 1.1.2-2.el7                  base     71 k
 libXrender                   x86_64 0.9.10-1.el7                 base     26 k
 libXt                        x86_64 1.1.5-3.el7                  base    173 k
 libXt-devel                  x86_64 1.1.5-3.el7                  base    446 k
 libXtst                      x86_64 1.2.3-1.el7                  base     20 k
 libXxf86vm                   x86_64 1.1.4-1.el7                  base     18 k
 libXxf86vm-devel             x86_64 1.1.4-1.el7                  base     18 k
 libarchive                   x86_64 3.1.2-10.el7_2               base    318 k
 libdrm                       x86_64 2.4.74-1.el7                 base    146 k
 libdrm-devel                 x86_64 2.4.74-1.el7                 base    120 k
 libedit                      x86_64 3.0-12.20121213cvs.el7       base     92 k
 libfontenc                   x86_64 1.1.3-3.el7                  base     31 k
 libgnome-keyring             x86_64 3.12.0-1.el7                 base    109 k
 libgomp                      x86_64 4.8.5-16.el7                 base    154 k
 libjpeg-turbo                x86_64 1.2.90-5.el7                 base    134 k
 libmpc                       x86_64 1.0.1-3.el7                  base     51 k
 libpciaccess                 x86_64 0.13.4-3.el7_3               base     26 k
 libpng                       x86_64 2:1.5.13-7.el7_2             base    213 k
 libstdc++-devel              x86_64 4.8.5-16.el7                 base    1.5 M
 libtiff                      x86_64 4.0.3-27.el7_3               base    170 k
 libwebp                      x86_64 0.3.0-7.el7                  base    170 k
 libxcb                       x86_64 1.12-1.el7                   base    211 k
 libxcb-devel                 x86_64 1.12-1.el7                   base    1.0 M
 libxshmfence                 x86_64 1.2-1.el7                    base    7.2 k
 libxslt                      x86_64 1.1.28-5.el7                 base    242 k
 lksctp-tools                 x86_64 1.0.17-2.el7                 base     88 k
 lyx-fonts                    noarch 2.2.3-1.el7                  epel    159 k
 lzo                          x86_64 2.06-8.el7                   base     59 k
 mesa-libGL                   x86_64 17.0.1-6.20170307.el7        base    155 k
 mesa-libGL-devel             x86_64 17.0.1-6.20170307.el7        base    151 k
 mesa-libGLU                  x86_64 9.0.0-4.el7                  base    196 k
 mesa-libGLU-devel            x86_64 9.0.0-4.el7                  base    9.0 k
 mesa-libglapi                x86_64 17.0.1-6.20170307.el7        base     41 k
 mpfr                         x86_64 3.1.1-4.el7                  base    203 k
 openssh                      x86_64 7.4p1-13.el7_4               updates 509 k
 openssh-clients              x86_64 7.4p1-13.el7_4               updates 654 k
 perl                         x86_64 4:5.16.3-292.el7             base    8.0 M
 perl-Carp                    noarch 1.26-244.el7                 base     19 k
 perl-Encode                  x86_64 2.51-7.el7                   base    1.5 M
 perl-Error                   noarch 1:0.17020-2.el7              base     32 k
 perl-Exporter                noarch 5.68-3.el7                   base     28 k
 perl-File-Path               noarch 2.09-2.el7                   base     26 k
 perl-File-Temp               noarch 0.23.01-3.el7                base     56 k
 perl-Filter                  x86_64 1.49-3.el7                   base     76 k
 perl-Getopt-Long             noarch 2.40-2.el7                   base     56 k
 perl-Git                     noarch 1.8.3.1-12.el7_4             updates  53 k
 perl-HTTP-Tiny               noarch 0.033-3.el7                  base     38 k
 perl-PathTools               x86_64 3.40-5.el7                   base     82 k
 perl-Pod-Escapes             noarch 1:1.04-292.el7               base     51 k
 perl-Pod-Perldoc             noarch 3.20-4.el7                   base     87 k
 perl-Pod-Simple              noarch 1:3.28-4.el7                 base    216 k
 perl-Pod-Usage               noarch 1.63-3.el7                   base     27 k
 perl-Scalar-List-Utils       x86_64 1.27-248.el7                 base     36 k
 perl-Socket                  x86_64 2.010-4.el7                  base     49 k
 perl-Storable                x86_64 2.45-3.el7                   base     77 k
 perl-TermReadKey             x86_64 2.30-20.el7                  base     31 k
 perl-Text-ParseWords         noarch 3.29-4.el7                   base     14 k
 perl-Time-HiRes              x86_64 4:1.9725-3.el7               base     45 k
 perl-Time-Local              noarch 1.2300-2.el7                 base     24 k
 perl-constant                noarch 1.27-2.el7                   base     19 k
 perl-libs                    x86_64 4:5.16.3-292.el7             base    688 k
 perl-macros                  x86_64 4:5.16.3-292.el7             base     43 k
 perl-parent                  noarch 1:0.225-244.el7              base     12 k
 perl-podlators               noarch 2.5.1-3.el7                  base    112 k
 perl-threads                 x86_64 1.87-4.el7                   base     49 k
 perl-threads-shared          x86_64 1.43-6.el7                   base     39 k
 python-babel                 noarch 0.9.6-8.el7                  base    1.4 M
 python-backports             x86_64 1.0-8.el7                    base    5.8 k
 python-backports-ssl_match_hostname
                              noarch 3.4.0.2-4.el7                base     12 k
 python-docutils              noarch 0.11-0.2.20130715svn7687.el7 base    1.5 M
 python-javapackages          noarch 3.4.1-11.el7                 base     31 k
 python-jinja2                noarch 2.7.2-2.el7                  base    515 k
 python-lxml                  x86_64 3.2.1-4.el7                  base    758 k
 python-markupsafe            x86_64 0.11-10.el7                  base     25 k
 python-pillow                x86_64 2.0.0-19.gitd1c6db8.el7      base    438 k
 python-pygments              noarch 1.4-10.el7                   base    599 k
 python-setuptools            noarch 0.9.8-7.el7                  base    397 k
 rsync                        x86_64 3.0.9-18.el7                 base    360 k
 ttmkfdir                     x86_64 3.0.9-42.el7                 base     48 k
 tzdata-java                  noarch 2017c-1.el7                  updates 183 k
 xorg-x11-font-utils          x86_64 1:7.5-20.el7                 base     87 k
 xorg-x11-fonts-Type1         noarch 7.5-9.el7                    base    521 k
 xorg-x11-proto-devel         noarch 7.7-20.el7                   base    284 k
 zlib-devel                   x86_64 1.2.7-17.el7                 base     50 k

 Non-Package-Managed Dependencies:
 Boost                        x86_64 1.61.0
 Truelight                    x86_64 4.0.7863
 OpenEXR                      x86_64 2.2.1
 OpenImageIO                  x86_64 1.7.x
```

### CODE REVIEW

**Comment by dbr** [comment]
Cool! Seems to work for me - built in around 25minutes (on 2 cores of a 2.3GHz i5 Macbook Pro)

Probably want to run `yum clean all` and remove the `/home/downloads` and `/home/git` (seems to bring the image down to about 1.3GB)

In `share/docker/` I ran:

    docker build . -t ocio:centos7_gcc48 -f dockerfile_centos7_gcc48

    docker run --volume $PWD/../../:/src/ociosrc -t ocio:centos7_gcc48 bash -c 'mkdir /build && cd /build && cmake3 /src/ociosrc && make -j2`

..and it seemed to build OCIO successfully

**Comment by scoopxyz** [comment]
great! Yes you're right I'll add the cleanup steps, that'll help make the download more accessible.

Any opinions on the structure / order of the Dockerfiles? I'd like some sort of naming convention that's sensible, currently doing `dockerfile_<os>_<compiler>` however once there are additional elements to the matrix (oiio version, boost version, etc) the filename gets unwieldy

**Comment by hodoulp** [comment]
Partial investigation results:
1. boost compilation command ```./b2 install -j2 variant=release --with-system --with-regex --with-filesystem --with-thread --with-python --prefix=/usr/local``` is far enough for OIIO. It greatly speedup the boost compilation time and reduces the disk space
2. ```python-sphinx``` should not be usefull as OCIO owns it ?
3. ```truelight-4.0.7863`` does not provide header files ?

**Comment by scoopxyz** [comment]
Thanks, I'll make those modifications as well.

Yes, I realized that Truelight doesn't provide the header files, not sure where you get them?

**Comment by dbr** [comment]
The OCIO installation docs mention "Truelight SDK" which sounds like a distinct thing.. but the only reference I can find to this is various mirrors of the OCIO docs

@malcolmhumphreys would presumably know where the SDK can be acquired. If not, maybe contact Filmlight's support?

**Comment by scoopxyz** [comment]
I'm fairly certain now that you need to buy a license before getting access to the API.

**Comment by malcolmhumphreys** [comment]
Yes you need to a lic to access the true light sdk / api. It would be
interesting to see if anyone actually is using this as it could be retired.

**Pull request merged**
